### ISSUE TITLE
Manage cohort type – on the search result page 

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#18]
Manage cohort type – on the search result page – try to search a record that does not exist into the system – error message “No record(s) found should be appeared. (The same bug should be fixed in all the other modules).

![image](https://cloud.githubusercontent.com/assets/20788534/17326463/0867aafc-58cb-11e6-8a28-cbb431fbb996.png)

**Comment by bholagabbar** [comment]
fixed in commit https://github.com/OpenSRP/openmrs-module-cohort/commit/bbef5b767d10575d34ea8b98dffed852ec903d73

**Comment by zohaibihs** [comment]
Manage Cohort Attributes Type – on the search result page – try to search a record that does not exist into the system – error message “No record(s) found should be appeared. 

![image](https://cloud.githubusercontent.com/assets/20788534/17806757/d3734344-661f-11e6-8cf1-03099567f4b1.png)

**Comment by bholagabbar** [comment]
Why reopen this? Search for an invalid entry and it will show the message.
If you are submitting an empty field, there will be an alert box saying
'please full this up'

On 19-Aug-2016 3:46 PM, "zohaibihs" notifications@github.com wrote:

Reopened #18 https://github.com/OpenSRP/openmrs-module-cohort/issues/18.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/OpenSRP/openmrs-module-cohort/issues/18#event-761079293,
or mute the thread

**Comment by zohaibihs** [comment]
It's working fine on other module but still not working on Manage cohort attributes type.

**Comment by bholagabbar** [comment]
It won't because module would have to be redeployed...

**Comment by bholagabbar** [comment]
Actually rebuilt from source and redeployed. I have made changes in the
source
